; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stack-sticks3

[env:env]
build_flags =
    -DREFRESH_MS=300000
    -DWIFI_TIMEOUT=15000
    -DNTP_TIMEOUT=10000
    -DMQTT_STATUS_TIMEOUT=8000
    -DCOL_HEADER=0x1A74
    -DCOL_ACCENT=0x07FF
    -DRC_EXPO_MID_PCT=50
    -DRC_EXPO_ENABLED=1
    -DSERIAL_BAUD=115200

[env:m5stack-sticks3]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env:env.build_flags}
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DBOARD_M5STICKS3=1
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
monitor_speed = 115200
lib_deps =
    M5Unified=https://github.com/m5stack/M5Unified
    M5PM1=https://github.com/m5stack/M5PM1
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8
